GET http://localhost:3000/programation/filter?channelCategory=Filmes&programCategory=Filme/Terror&initialProgramationDate=2022-07-15 15:00&finalProgramationDate=2022-07-16 00:00

&programName=Batman&channelName=HBO Plus